### ISSUE TITLE
What versions does awa-ssh work with?

### ISSUE THREAD

**Issue by wiml** [haesbaert/awa-ssh#7]
I've been trying to install awa-ssh using opam, but so far without success.

* Awa requires a newer version of `nocrypto` than the current release (0.5.4).
* If I upgrade to the dev head of nocrypto, I can no longer install `x509` (val ca_error_of_sexp : Ppx_sexp_conv_lib.Sexp.t -> ca_error is not included in val ca_error_of_sexp : Sexplib.Sexp.t -> ca_error).
* I've tried downgrading various other packages but have not found a combination of versions that will allow awa to build.

**Comment by hannesm** [comment]
so, what works for me is:
- nocrypto pinned to https://github.com/hannesm/ocaml-nocrypto.git#awa-future
- x509 pinned to https://github.com/hannesm/ocaml-x509.git#future
- tls (and tls-lwt / tls-mirage) pinned to https://github.com/hannesm/ocaml-tls.git#future
- awa-ssh from my branch (see #8) https://github.com/hannesm/awa-ssh.git#future
--> the tests (for some reason not the e2e test) and awa_test_client.exe / awa_test_server.exe work fine then

**Comment by dsheets** [comment]
With Ocaml 4.08.1, I also had to downgrade cstruct from 5.0.0 to 4.0.0 due to
```
File "_none_", line 1:
Error (alert deprecated): module Stdlib.Pervasives
Use Stdlib instead.

If you need to stay compatible with OCaml < 4.07, you can use the
stdlib-shims library: https://github.com/ocaml/stdlib-shims
```

that apparently comes from the cstruct PPX. Something in dune or the ppx (?) seems to lose the lexical coordinates. The source of this problem was more annoying to figure out than necessary but now I am running a testing SSH server -- hooray!

**Comment by hannesm** [comment]
@dsheets good to hear. I use `dune build --profile=release` quite a lot to not be disturbed by "warnings are errors" (and indeed, that cstruct/ppx_cstruct issue is annoying, I PRed a fix for the above 3 weeks ago in https://github.com/mirage/ocaml-cstruct/pull/269)

**Comment by hannesm** [comment]
since c0e82546abe73c074f58f61388efaae7f6650117 mirage-crypto is used now (which in turn has been released to opam repository)
